[web]
web1 ansible_host=10.10.0.30
web2 ansible_host=10.20.0.6

[prometheus]
prometheus ansible_host=10.20.0.22

[grafana]
grafana ansible_host=10.20.0.34

[elasticsearch]
elasticsearch ansible_host=10.30.0.11

[kibana]
kibana ansible_host=10.30.0.22 public_ip=111.88.157.172

[all:vars]
ansible_user=dvp
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args=-o ProxyJump=dvp@93.77.179.47
